provider: leitstand.io
description: DNS record management views
controller: controller.js
extensions:
# Add main menu item to list all DNS zones.
- extend: 
    module: inventory
    menu: main
    after: racks
  items:
  - item: dns
    label: DNS Zones
    title: Manage DNS zones
    scopesAllowed:
    - ivt
    - ivt.read
    - ivt.element
    - ivt.element.read
    - ivt.element.dns
    view: zones.html
# Add DNS record menu item to the element menu
- extend:
    module: inventory
    menu: element
    after: element-ifl
  items:
  - item: element-dns
    label: DNS
    title: Manage DNS records
    view: element-dns-records.html
# Add menu to manage a DNS zone     
- extend:
    module: inventory
    after: main
  menus:
  - menu: dns
    label: DNS Zone
    title: Manage a DNS Zone
    scopesAllowed:
      - ivt
      - ivt.read
      - ivt.element
      - ivt.element.read
    requires:
    - dns_zone_id
    query:
     zone: "{{dns_zone_id}}"
    items:
    - item: zone-settings
      label: Settings
      title: Manage DNS zone settings
      view: zone-settings.html
    - item: zone-elements
      label: Elements
      title: View elements with DNS records bound to this zone
      view: zone-elements.html          