provider: leitstand.io
description: DNS record management views
controller: controller.js
extensions:
# Add DNS record menu item to the element menu
- extend:
    module: inventory
    menu: element
    before: element-location
  items:
  - item: element-dns
    label: DNS
    title: Manage DNS records
    view: element-dns-records.html        