module: inventory
menus:
- menu: main
  items:
  - item: pods
    label: Pods
    title: Search all pods in the network
    scopesAllowed:
    - ivt
    - ivt.read
    - ivt.group
    - ivt.group.read
    view: pods.html
  - item: elements
    label: Elements
    title: Search all elements in the network
    scopesAllowed:
    - ivt
    - ivt.read
    - ivt.element
    - ivt.element.read
    view: elements.html
  - item: ifps
    label: Interfaces
    title: Search all physical interfaces in the network
    scopesAllowed:
    - ivt
    - ivt.read
    - ivt.element
    - ivt.element.read
    view: ifps.html
- menu: meta
  label: Administration
  title: Maintain roles and platforms
  scopesAllowed:
  - ivt
  - ivt.read
  - ivt.element
  - ivt.element.read
        